replicas: 2
resources:
  requests:
    cpu: "3000m"
    memory: "4Gi"
  limits:
    cpu: "3000m"
    memory: "4Gi"
volumeClaimTemplate:
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
sysctlInitContainer:
  enabled: false
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: true
    xpack.security.transport.ssl.enabled: true
extraEnvs:
  - name: ELASTIC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: password
  - name: ELASTIC_USERNAME
    valueFrom:
      secretKeyRef:
        name: elastic-credentials
        key: username