apiVersion: v1
kind: Secret
metadata:
  name: airflow-postgresql-backend-credentials
  namespace: airflow
type: Opaque
data:
  connection: {{ "db+postgresql://user:pass@host:5432/db?sslmode=disable" | b64enc }}