---
- name: Create VM from template
  hosts: localhost
  vars_files:
    - ../../group_vars/vcenter-credentials.yml
    - ../../temp_vars/vsphere-create-vm-vars.yml

  tasks:
    - name: Create VM from template
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: false

        datacenter: "{{ vm_datacenter }}"
        folder: "{{ vm_folder }}"
        name: "{{ vm_hostname }}"
        state: present
        template: "template-{{ vm_centos_version }}"

        esxi_hostname: "{{ vm_esxi }}"
        networks:
          - name: "{{ vm_network_name }}"
            ip: "{{ vm_ip }}"
            gateway: "{{ vm_gateway }}"
            netmask: "{{ vm_netmask }}"
        wait_for_ip_address: true
        customization:
          hostname: "{{ vm_hostname }}"
          dns_servers: ["{{vm_dns}}"]
        hardware:
          memory_mb: "{{ vm_memory_mb }}"
          num_cpus: "{{ vm_num_cpus }}"
        disk:
          - size_gb: "{{ vm_disk_size }}"
            type: eagerzeroedthick
            datastore: "{{ vm_datastore }}"
      register: vm_facts

    - name: Debug
      debug:
        var: vm_facts

    - name: Add new host
      add_host:
        name: "{{ vm_hostname }}"
        hostname: "{{ vm_ip }}"
        groups: common
