---
- name: Create VM from template
  hosts: localhost
  vars_files:
  - ../../group_vars/vsphere/credentials.yml
  - ../../group_vars/vsphere/create-vm.yml

  tasks:
  - name: Create VM
    ansible.builtin.vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: false

      datacenter: "{{ vm_datacenter }}"
      folder: "{{ vm_folder }}"
      name: "{{ vm_hostname }}"
      state: present
      template: "template-{{ vm_centos_version }}"
      esxi_hostname: "{{ vm_esxi }}"

      networks:
        - name: "{{ vm_network_name }}"
          ip: "{{ vm_ip }}"
          gateway: "{{ vm_gateway }}"
          netmask: "{{ vm_netmask }}"
      wait_for_ip_address: true
      customization:
        hostname: "{{ vm_hostname }}"
        dns_servers: "{{ vm_dns }}"
      hardware:
        memory_mb: "{{ vm_memory_mb }}"
        num_cpus: "{{ vm_num_cpus }}"
      disk:
        - size_gb: "{{ vm_disk_size }}"
          type: eagerzeroedthick
          datastore: "{{ vm_datastore }}"
    register: vm_facts

  - name: Заполняем аттрибуты
    vmware_guest_custom_attributes:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: false

      name: "{{ vm_hostname }}"
      uuid: "{{ vm_facts.instance.hw_product_uuid }}"
      state: present
      attributes:
        - name: "Owner"
          value: "{{ vm_attr_owner }}"
        - name: "Owner email"
          value: "{{ vm_attr_owner_email }}"
        - name: "Co_owner"
          value: "{{ vm_attr_co_owner }}"
        - name: "Co_owner email"
          value: "{{ vm_attr_co_owner_email }}"
        - name: "ExpireDate"
          value: "{{ vm_attr_expiredate }}"
        - name: "Practice"
          value: "{{ vm_attr_practice }}"
        - name: "Project code"
          value: "{{ vm_attr_practice }}"
