apiVersion: v1
kind: Secret
metadata:
  name: elastic-credentials
type: Opaque
data:
  username: {{ .Values.elasticsearch.credentials.username | b64enc }}
  password: {{ .Values.elasticsearch.credentials.password | b64enc }}
