apiVersion: v1
kind: Secret
metadata:
  name: camunda-bpm-platform-postgresql-credentials
  namespace: camunda
type: Opaque
data:
  DB_USERNAME: {{ "camunda" | b64enc }}
  DB_PASSWORD: {{ "camunda$4" | b64enc }}
